service: project-hunt-api

provider:
  name: google
  stage: prod
  runtime: nodejs8
  region: us-central1
  project: graph-intelligence
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  credentials: /Users/milanarezina/WebstormProjects/sidesideproject/api/graph-intelligence-e29273f12d3b.json

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  search-projects:
    handler: searchProjects
    events:
      - http: path
